kind: Template
apiVersion: v1
labels:
  template: hello2-dev-deployment
  group: hello2-dev-deployment
  application: hello2
  environment: dev
metadata:
  name: hello2-dev-deployment
message: hello2 Stage Deployment

objects:
#APPLICATION
- kind: Service
  apiVersion: v1
  metadata:
    name: "hello2-svc"
  spec:
    ports:
    - name: "hello2-svc"
      port: 9000
      targetPort: 9000
    selector:
      name: "hello2-dc"
    sessionAffinity: None

#Application Route
- kind: Route
  apiVersion: v1
  metadata:
    name: hello2-rt
  spec:
    to:
      kind: Service
      name: "hello2-svc"

# Application ImageStream
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "hello2-is"
  spec:
#    dockerImageRepository: "/hello2"
    dockerImageRepository: ""
#    tags:
#    - from:
#      kind: dockerImageRepository
#      name: "/hello2:0.0"
    importPolicy:
      insecure: true
    name: latest

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "hello2-dc"
  spec:
    replicas: 1
    selector:
      name: "hello2-dc"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "hello2-dc"
      spec:
        containers:
        - name: hello2
          image: "hello2-is"
          ports:
          - containerPort: 9000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /hello-world
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /hello-world
              port: 9000
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 2
            seccessThreashold: 1
            failureThreashold: 5
          resources:
            limits:
              memory: 512Mi
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "hello2"
        from:
          kind: ImageStream
          name: "hello2-is"
